### ISSUE TITLE
add text blocks

### ISSUE THREAD

**Issue by michael-ciniawsky** [static-dev/html-whitespace-parser#14]
```
p.
  Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut 
  labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris
  nisi ut aliquip ex ea commodo.
```

**Comment by jescalan** [comment]
So you will need some extra syntax for this, I'd recommend a `.` after the tag containing a text block as jade does (and was implemented in reshape). This turned out actually to be quite a difficult implementation, [here's a reference](https://github.com/reshape/sugarml/blob/master/lib/lexer.js#L180) in case this helps!

**Comment by michael-ciniawsky** [comment]
@jescalan  👍
